project_name: utask

builds:
  - binary: utask
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -mod=vendor
    ldflags:
      - -X ${VERSION_PKG}.Commit=${LAST_COMMIT} -X ${VERSION_PKG}.Version=${VERSION}"
    goos:
      - darwin
      - linux
      - openbsd

    goarch:
      - amd64

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    linux: Linux
    amd64: x86_64

release:
  github:
    owner: ovh
    name: utask
  draft: true
