FROM ovhcom/utask:1.0.0 AS builder

COPY .  /go/src/github.com/ovh/utask
WORKDIR /go/src/github.com/ovh/utask
RUN make

FROM ovhcom/utask:1.0.0 # TODO switch to lighter base image, discard source code

COPY templates  /app/templates
COPY --from=builder /go/src/github.com/ovh/utask/plugins /app/plugins
COPY --from=builder /go/src/github.com/ovh/utask/init    /app/init
COPY --from=builder /go/src/github.com/ovh/utask/utask   /app/utask
RUN chmod +x /app/utask
