// Code generated by "stringer -type=OutputStrategy --trimprefix=OutputStrategy"; DO NOT EDIT.

package executor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OutputStrategynone-0]
	_ = x[OutputStrategymerge-1]
	_ = x[OutputStrategytemplate-2]
}

const _OutputStrategy_name = "nonemergetemplate"

var _OutputStrategy_index = [...]uint8{0, 4, 9, 17}

func (i OutputStrategy) String() string {
	if i < 0 || i >= OutputStrategy(len(_OutputStrategy_index)-1) {
		return "OutputStrategy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OutputStrategy_name[_OutputStrategy_index[i]:_OutputStrategy_index[i+1]]
}
